/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(rtty_decode_ff.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c410560c6e978c5077fd9204a7c83f3a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/rtty/rtty_decode_ff.h>
// pydoc.h is automatically generated in the build directory
#include <rtty_decode_ff_pydoc.h>

void bind_rtty_decode_ff(py::module& m)
{

    using rtty_decode_ff    = ::gr::rtty::rtty_decode_ff;


    py::class_<rtty_decode_ff, gr::block, gr::basic_block,
        std::shared_ptr<rtty_decode_ff>>(m, "rtty_decode_ff", D(rtty_decode_ff))

        .def(py::init(&rtty_decode_ff::make),
           py::arg("rate"),
           py::arg("baud"),
           py::arg("polarity"),
           D(rtty_decode_ff,make)
        )
        



        ;




}








